return {
  { "flash.nvim", enabled = false },
  { "friendly-snippets", enabled = false },
  { "bufferline.nvim", enabled = false },
  { "vim-dadbod", enabled = false },
  { "vim-dadbod-completion", enabled = false },
  { "vim-dadbod-ui", enabled = false },
  { "mini.ai", enabled = false },
  { "mini.diff", enabled = false },
  { "mini.icons", enabled = false },
  { "lazydev.nvim", enabled = false },
  { "render-markdown.nvim", enabled = false },
  { "persistence.nvim", enabled = false },
  { "SchemaStore.nvim", enabled = false },
  { "venv-selector.nvim", enabled = false },
  { "tpope/vim-fugitive", enabled = false },
  { "NeogitOrg/neogit", dependencies = { "nvim-lua/plenary.nvim" } },
}
